#!/bin/bash

# wrapper script to execute commands within the shell docker container
#
# Example:
#       docker-stack-shell echo "Hello world"
#

# uncomment to debug
#set -x

# fail on any error
set -o errexit

# run actual command inside dockerized shell
docker-compose run shell true && "$@"

# exit cleanly
exit 0