# doma environment
# ================

COMPOSE_PROJECT_NAME 	?= phpnginx
PROJECT_REGISTRY     	?= docker.io
STACK_YML_DIR 			?= .
COMPOSE_FILE			?= docker-compose.yml
APP_NAME                ?=
WEB_SEVICE_SUFFIX       ?= web

include $(DOMA_DIR)/docker/Makefile
