# Dockerfile for PHP-FPM built for PHP/Nginx/Memcache docker-stack
# ===============================================================
#   docker build -t neam/docker-stack-php:5.6.6-fpm

FROM schmunk42/php-yii2:fpm

# Included in base image already:
#   intl
#   gd
#   pdo_mysql
#   mbstring
#   mcrypt
#   zip
#   acpu (pecl)

# Install some additional PHP extensions
RUN true \
    && docker-php-ext-install curl       \
    && pecl install redis && echo extension=redis.so > /usr/local/etc/php/conf.d/redis.ini \
    && pecl install mongo && echo extension=mongo.so > /usr/local/etc/php/conf.d/mongo.ini \
    && docker-php-ext-install xsl

WORKDIR /opt

# First. Install libmemcached
ENV LIBMEMCACHED_VERSION 1.0.18
RUN curl -LO http://launchpad.net/libmemcached/1.0/$LIBMEMCACHED_VERSION/+download/libmemcached-$LIBMEMCACHED_VERSION.tar.gz \
    && tar -xzvf libmemcached-$LIBMEMCACHED_VERSION.tar.gz \
    && cd libmemcached-$LIBMEMCACHED_VERSION \
    && ./configure \
    && make \
    && make install

# Secondly, Install PECL memcached
ENV PECL_MEMCACHED_VERSION 2.2.0
RUN pecl download memcached-$PECL_MEMCACHED_VERSION \
    && tar zxvf memcached-$PECL_MEMCACHED_VERSION.tgz \
    && cd memcached-$PECL_MEMCACHED_VERSION \
    && phpize \
    && ./configure --with-libmemcached-dir=/opt/libmemcached-$LIBMEMCACHED_VERSION/libmemcached

# Install newrelic PHP extension
# TODO https://download.newrelic.com/php_agent/release/newrelic-php5-4.19.0.90-linux.tar.gz /usr/src/newrelic
