#!/bin/bash

# Uncomment or set env var to debug
#DOCKERSTACK_DEBUG=1

if [ "$DOCKERSTACK_DEBUG" == "1" ]; then
    set -x;
fi

export APP_HOME="$(pwd)"
export SCRIPTDIR="$(dirname $0)"

# Source local env vars if .env-file is available
[ -f ".env" ] && source .env

# Auto-detect docker-stack installation
if [ "$DOCKER_STACK_SRC" == "" ]; then

    function chk {
        if [ -d "$1" ]; then
            export DOCKER_STACK_SRC=$1
        fi
    }
    chk ~/.docker-stack
    chk bower_components/docker-stack
    chk node_modules/docker-stack
    chk vendor/neam/docker-stack
    chk ./.docker-stack
    chk ../docker-stack
    chk ../../docker-stack
    chk ../../../docker-stack

fi
if [ "$DOCKER_STACK_SRC" == "" ]; then
    >&2 echo "Could not find a docker-stack installation"
    exit 1
fi

# Source local docker stack vars if .docker-stack-file is available
[ -f ".docker-stack" ] && source .docker-stack

# Auto-detect local stack yml
if [ "$LOCAL_STACK_YML" == "" ]; then

    function chk {
        if [ -f "$1" ]; then
            export LOCAL_STACK_YML=$1
        fi
    }

    chk vendor/neam/docker-stack/stacks/hello-world/docker-compose.yml
    chk ./stack/local.yml
    chk ./docker-compose.yml

fi

# Auto-detect production stack yml
if [ "$PRODUCTION_STACK_YML" == "" ]; then

    function chk {
        if [ -f "$1" ]; then
            export PRODUCTION_STACK_YML=$1
        fi
    }

    chk vendor/neam/docker-stack/stacks/hello-world/docker-compose.yml
    chk ./stack/deploy.yml
    chk ./docker-compose-production.yml

fi

# Auto-detect tutum stack yml
if [ "$TUTUM_STACK_YML" == "" ]; then

    function chk {
        if [ -f "$1" ]; then
            export TUTUM_STACK_YML=$1
        fi
    }

    chk vendor/neam/docker-stack/stacks/hello-world/docker-compose.yml
    chk ./stack/deploy-tutum.yml
    chk ./docker-compose-tutum.yml

fi

# Run the actual command

case $1 in
"select" | "list" | "install")
    bash $DOCKER_STACK_SRC/cli/$1.sh ${*:2}
    exit 0
    ;;
"info")
    echo APP_HOME=$APP_HOME;
    echo DOCKER_STACK_SRC=$DOCKER_STACK_SRC;
    echo LOCAL_STACK_YML=$LOCAL_STACK_YML;
    echo PRODUCTION_STACK_YML=$PRODUCTION_STACK_YML;
    echo TUTUM_STACK_YML=$TUTUM_STACK_YML;
    exit 0;
    ;;
"local")
    if [ "$LOCAL_STACK_YML" == "" ]; then
        >&2 echo "Could not find the local stack yml"
        exit 1
    fi
    export STACK_YML=$LOCAL_STACK_YML;
    ;;
"production")
    if [ "$PRODUCTION_STACK_YML" == "" ]; then
        >&2 echo "Could not find the production stack yml"
        exit 1
    fi
    export STACK_YML=$PRODUCTION_STACK_YML;
    ;;
"tutum")
    if [ "$TUTUM_STACK_YML" == "" ]; then
        >&2 echo "Could not find the tutum stack yml"
        exit 1
    fi
    export STACK_YML=$TUTUM_STACK_YML;
    ;;
*)
    >&2 echo "Unknown command: $1"
    exit 1
    ;;
esac

case $2 in
"url")
    bash $DOCKER_STACK_SRC/cli/$2.sh ${*:3}
    ;;
*)
    docker-compose -f $STACK_YML ${*:2}
    ;;
esac

exit 0
