#!/bin/bash

BUILD_DIR="$2"
basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source $basedir/../bin/common.sh

function requires_laravel() {
  require_change=$(jq --raw-output ".require[\"laravel/framework\"] // \"\"" < "$BUILD_DIR/composer.json")
  [ -n  "$require_change" ]
}

case "$1" in
  detect)
    if [ ! -f "$BUILD_DIR/composer.json" ]; then
      exit 1
    fi

    if requires_laravel; then
      echo "-----> Detected Laravel app"
      exit 0
    else
      exit 1
    fi
    ;;
  get-log-files)
    echo "app/storage/logs/laravel.log"
    ;;
  compile)
    echo "-----> Setting up Laravel app"
    cp "$basedir/../conf/nginx/laravel.conf.erb" "$BUILD_DIR/conf/site.conf.erb"
    ;;
esac
