# doma environment
# ================

COMPOSE_PROJECT_NAME 	?= phundamenteco
PROJECT_REGISTRY     	?= docker.io
STACK_YML_DIR 			?= .
COMPOSE_FILE			?= docker-compose.yml

include $(DOMA_DIR)/docker/Makefile
